#!/bin/bash

# Introductory line
hostname=$(hostname)
username=$(whoami)
date_time=$(date | awk '{ print $4, $5 }')
echo -e "\nSystem Report for $hostname generated by $username, on $date_time"

echo ""

echo -e "System Information\n------------------"

# Next two lines is meant to identify OS information (not sure if applicable to other distros)
os_info=$(cat /etc/os-release | head -1 | awk -F = '{ print $2 }')
echo "OS: $os_info"

# Displays uptime information for host
uptime_info=$(uptime -p | awk '{ print $2, $3 }')
echo "Uptime: $uptime_info"

# Displays CPU information
cpu_info=$(lscpu | grep 'Model name' | awk -F : '{ print $2 }' | xargs)
echo "CPU: $cpu_info"

# Displays total RAM installed in host
mem_info=$(free -h | head -n 2 | tail -n 1 | awk '{ print $2 }')
echo "RAM: $mem_info"

# Displays disk information
disk_info=$(lsblk -do TYPE,NAME,VENDOR,MODEL,SIZE | awk '$1 == "disk" ' | xargs | cut -d' ' -f3-)
echo "Disk(s): $disk_info"

# Displays video/monitor device information
video_info=$(lspci | grep 'VGA\|DIsplay' | awk -F : '{ print $3 }' | xargs)
echo "Video: $video_info"

# The next four lines display IP address information followed by the default gateway
ip_addr_info=$(ip route | grep default | cut -d' ' -f9)
echo "Host Address: $ip_addr_info"
default_gw_info=$(ip route | grep default | cut -d' ' -f3)
echo "Gateway IP: $default_gw_info"


# Displays DNS server information
dns_info=$(cat /etc/resolv.conf | grep nameserver | cut -d' ' -f2-)
echo "DNS Server: $dns_info"

echo ""

echo -e "System Status\n------------------"

# Displays users logged in currently
login_users=$(w -hs | awk '{ print $1 }')
echo "Users Logged In: $login_users"

# Displays free disk space
disk_space=$(df -hl --output=target,avail | sed -e '1d')
echo -e "Disk Space: \n$disk_space\n"

# Displays how many processes are running in the background
process_count=$(ps -sh | wc -l)
echo "Process Count: $process_count"

# Displays load average in current time
load_ave=$(uptime | awk -F'load average: ' '{ print $2 }')
echo "Load Averages: $load_ave"

# Displays open ports
ports_open=$(ss -tulnH | awk '{ print $5 }' | rev | awk -F: '{ print $1 }' | rev)
echo -e "Listening Network Ports:\n$ports_open\n"

# Displays firewall status
ufw_status=$(sudo ufw status | cut -d' ' -f2)
echo "UFW Status: $ufw_status"
