#!/bin/bash

# Introductory line
hostname=$(hostname)
username=$(whoami)
date_time=$(date | awk '{ print $4, $5 }')

# Next two lines is meant to identify OS information (not sure if applicable to other distros)
os_info=$(cat /etc/os-release | head -1 | awk -F = '{ print $2 }')

# Displays uptime information for host
uptime_info=$(uptime -p | awk '{ print $2, $3 }')

# Displays CPU information
cpu_info=$(lscpu | grep 'Model name' | awk -F : '{ print $2 }' | xargs)

# Displays total RAM installed in host
mem_info=$(free -h | head -n 2 | tail -n 1 | awk '{ print $2 }')

# Displays disk information
disk_info=$(lsblk -do TYPE,NAME,VENDOR,MODEL,SIZE | awk '$1 == "disk" ' | xargs | cut -d' ' -f3-)

# Displays video/monitor device information
video_info=$(lspci | grep 'VGA\|DIsplay' | awk -F : '{ print $3 }' | xargs)

# The next four lines display IP address information followed by the default gateway
ip_addr_info=$(ip route | grep default | cut -d' ' -f9)
default_gw_info=$(ip route | grep default | cut -d' ' -f3)

# Displays DNS server information
dns_info=$(cat /etc/resolv.conf | grep nameserver | cut -d' ' -f2-)

# Displays users logged in currently
login_users=$(w -hs | awk '{ print $1 }')

# Displays free disk space
disk_space=$(df -hl --output=source,avail -x tmpfs | sed -e '1d' | sed 's/^/\t\t/g')

# Displays how many processes are running in the background
process_count=$(ps -Sh | wc -l)

# Displays load average in current time
load_ave=$(uptime | awk -F'load average: ' '{ print $2 }')

# Displays open ports
ports_open=$(ss -tulnH | awk '{ print $5 }' | grep -Eo [0-9]+$ | sed -z 's/\n/, /g;s/, $/\n/')

# Displays firewall status
ufw_status=$(sudo ufw status | cut -d' ' -f2)



# This is the output of the script
cat <<EOF

System Report for $hostname generated by $username, on $date_time

System Information
------------------
OS: $os_info
Uptime: $uptime_info
CPU: $cpu_info
RAM: $mem_info
Disk(s): $disk_info
Video: $video_info
Host Address: $ip_addr_info
Gateway IP: $default_gw_info
DNS Server: $dns_info

System Status
------------------
Users Logged In: $login_users
Disk Space: 
$disk_space
Process Count: $process_count
Load Averages: $load_ave
Listening Network Ports: $ports_open 
UFW Status: $ufw_status

EOF
